spawn("sconfig")
expect("输入数字以选择选项:")
sendln("6")
expect("选择更新类别 (空白 = 取消):")
sendln("1")
expect("安装所有更新((A))，不安装更新( (空白 = 取消):")
sendln("a")
expect("是否立即重新启动? (是)或 (否):")
sendln("否")
expect("输入数字以选择选项:")
sendln("15")